version: '2'

services:
  system:
    image: greut/manyrails
    build: .
    hostname: capistrano
    ports:
      - "2222:22"
      - "8080:80"
    environment:
      - RUNIT=1
      - POSTGRES_PASSWORD=root
      - RACK_ENV=development
